# Generated by Django 4.2.2 on 2023-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="timestamp",
            field=models.TimeField(null=True),
        ),
    ]
