"""
Django settings for subtitles project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f%pg%#t7m&s=b0#(7p-4umf^3hjd8od2--h0&gytjt=ei89f=r"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "app.apps.AppConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "subtitles.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "subtitles.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# DIRECTRIES
CLI_DIR = "cli"
# OUTPUT_DIR = os.path.join(CLI_DIR, "output")
OUTPUT_DIR = "output"
# TEST_DIR = os.path.join(CLI_DIR, "tests")
TEST_DIR = "tests"

VTT_DIR = os.path.join(OUTPUT_DIR, "vtt")
XML_DIR = os.path.join(OUTPUT_DIR, "xml")
TXT_DIR = os.path.join(OUTPUT_DIR, "txt")
TEST_DATA_DIR = os.path.join(TEST_DIR, "data")

# FILENAMES
DEFAULT_TXT_FILENAME = "subtitles.txt"
DEFAULT_XML_FILENAME = "subtitles.xml"
DEFAULT_VTT_FILENAME = "subtitles.vtt"

# SERVICES
SERVICE_DISNEYPLUS = "disneyplus"
SERVICE_NETFLIX = "netflix"

# PARAMETERS
MAX_SEGMENTS = 75  # 3h = 360min, 5min/vtt, 360/5 = 75vtt
DOWNLOAD_INTERVAL = 0.5

# TESTS
TEST_TITLE = "test"
TEST_URL_DISNEYPLUS_00 = str(
    "https://raw.githubusercontent.com/astromech-droid/subtitles/main/tests/data"
    "/downloader/seg_00000.vtt"
)

TEST_URL_DISNEYPLUS_01 = str(
    "https://raw.githubusercontent.com/astromech-droid/subtitles/main/tests/data"
    "/downloader/seg_00001.vtt"
)

TEST_URL_NETFLIX = str(
    "https://raw.githubusercontent.com/astromech-droid/subtitles/main/tests/data"
    "/downloader/subtitles.xml"
)

TEST_LINES_XML: list[tuple[str]] = [
    ("00:13:25.000", "-Leave town for adventure. -[both] What did you say?"),
    ("00:10:21.454", "But we've been here for all time, since I was born!"),
    ("00:01:45.063", "You can handle a few minutes up here."),
    ("00:05:32.000", "I don't want him dicking you around tonight."),
    ("00:02:15.292", "I live at 308 Negra Arroyo Lane, Albuquerque, New Mexico, 87104."),
    ("01:00:08.980", "Appreciate it."),
]

TEST_LINES_VTT: list[tuple[str]] = [
    ("00:00:09.083", "(THEME MUSIC PLAYING)"),
    ("00:00:31.750", "BONNIE: <i>We're real proud of you, Judy.</i>"),
    ("00:00:33.333", "STU: Yeah, scared too. BONNIE: Yes."),
    (
        "00:34:36.120",
        "DARBUS: Timeliness means something in the world of theater, young lady.",
    ),
    ("00:18:55.520", "After all, she loves pi."),
]

TEST_DATABASE_TXT = [
    (1, "00:00:09", "(THEME MUSIC PLAYING)"),
    (2, "00:00:31", "BONNIE: <i>We're real proud of you, Judy.</i>"),
    (3, "00:00:33", "STU: Yeah, scared too. BONNIE: Yes."),
    (
        4,
        "00:34:36",
        "DARBUS: Timeliness means something in the world of theater, young lady.",
    ),
    (5, "00:18:55", "After all, she loves pi."),
]
